### ISSUE TITLE
Exception #<NoMethodError: undefined method `empty?' for false:FalseClass>

### ISSUE THREAD

**Issue by ebuildy** [logstash-plugins/logstash-filter-useragent#31]
- Version: Logstash 2.2
- Operating System: Linux

:message=>"Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.",
"exception"=>#<NoMethodError: undefined method `empty?' for false:FalseClass>

Here: https://github.com/logstash-plugins/logstash-filter-useragent/blob/master/lib/logstash/filters/useragent.rb#L99

I have no idea how logstash receives a useragent `false` , but it throws an error and stop logstash.

**Comment by agrawalramakant** [comment]
I am also facing this issue, and strangely this issue is still open since 1 year

**Comment by kares** [comment]
the master link is outdated, let's call it fixed by now :wink:

**Comment by shdubsh** [comment]
This is still an issue in logstash-filter-useragent 3.3.2.  It causes the pipeline to crash leading to denial of service.

To mitigate the outage, we used mutate with string templating to replace the boolean field with a string.

Stack:
```
{
  "message": "Pipeline worker error, the pipeline will be stopped",
  "exception": {
    "metaClass": {
      "metaClass": {
        "exception": "Java::OrgJrubyExceptions::NoMethodError",
        "backtrace": [
          "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_useragent_minus_3_dot_3_dot_2_minus_java.lib.logstash.filters.useragent.filter(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-useragent-3.3.2-java/lib/logstash/filters/useragent.rb:111)",
          "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.do_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159)",
          "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:178)",
          "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1821)",
          "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:175)",
          "org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:134)",
          "RUBY.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:299)"
        ],
        "thread": "#<Thread:0x40bdb6b8@/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:129 sleep>"
      }
    }
  },
  "pipeline_id": "main",
  "error": "(NoMethodError) undefined method `empty?' for false:FalseClass"
}
